### ISSUE TITLE
Tracking Issue M1/M2

### ISSUE THREAD

**Issue by mbeckem** [open-pioneer/trails-starter#35]
# Tracking Issue

## Organizational

-   [x] npm Organization @open-pioneer
-   [x] Setup build infrastructure, CI/CD: Tests, Linting, Automated Deployment
      -  [x] Repository setup: #8 
      -  [x] CI/CD: #5 
      -  [x] Commit hooks: #12
-   [x] Vulnerability checks
    -  [x] Nightly scans: #1 
    -  [x] Dependabot #13
-   [x] Separate packages into multiple repositories (starter, framework/buil40d-support): #40
-   [x] Scan licenses: #38
-   [x] Create license file: #44

## Vite setup

-   [x] Support monorepo structure (multiple apps and sites) in build output: #16 
-   [x] Generate metadata of app (package metadata, services, i18n, ...) as expected by runtime
    -   [x] Services: #18
    -   [x] Styles: #29
    -   [x] Properties: #25
    -   [x] I18N: #32

## Runtime environment

-   [x] Provide a web component #10
-   [x] Implement dependency injection for services
    -   [x] 1-to-1 dependencies: #11
    -   [x] 1-to-n dependencies: #39
-   [x] Implement support for properties in packages (and customization support for apps): #25
-   [x] Support for I18N
    -   [x] Research: I18N Framework, Document decision: #17
    -   [x] Implementation: #32
-   [x] Support for styles
-   [x] Provide an API as methods from the Web Component: #23
-   [x] Support for emitting events from the Web Component: #23
-   [x] #50
-   [x] Centralized logging: #24 
-   [x] #56 

## Dev Experience

-   [x] Ensure/Don't break HMR for react components
-   [x] Ensure HMR for css file changes: #47
-   [x] Support SCSS: #41
-   [x] #26
-   [x] #52 
-   [ ] (Debugging support: #46)

## UI Framework

-   [x] React Integration #10
-   [x] Research web component attributes / react integration: #2 
-   [x] React hooks 
    -   [x] Access Services: #22
    -   [x] Access package properties: #25 
    -   [x] Access package I18N #32 
-   [x] Component Framework integration
    -   [x] Research: Pick UI Framework and document decision: #14 
    -   [x] Implementation: #30 
-   [ ] Rich table for Chakra UI: #43

## Browser support

-   [x] Configure JavaScript targets for a reasonable set of browsers: #19

## OpenLayers integration

-   [x] Basic integration of openlayers (render map, load styles): #15 
-   [x] Basic package for open layers: #49
-   [ ] (Implement a simple demo toc)
-   [ ] (Implement ZoomToXYZ Control)
-   [ ] (Draw client side graphics)

## Other con terra services
-   [ ] (integrate with ct-proxy: redirect requests if necessary)
-   [ ] (integrate with ct-identity: add headers or query arguments if necessary)

## Documentation and Examples

-   [x] #55 
-   [x] Create internal developer documentation. Document guidelines and important implementation details.
    -   [x] Development Guidelines: #4
    -   [x] Init Architecture Documentation: #3 
    -   [x] Service Layer: #21
    -   [x] #42 
    -   [x] Build plugin #48
    -   [x] (react integration)
-   [x] Create public developer documentation:
    -   [x] Init Dev Guide: #9
    -   [x] Reference / Specs: "What is an app?" "What is a package?"
          -  [x] #20
    -   [x] Manual: app development, package development, deployment **TODO**
-   [ ] *Postponed* Build documentation of apps, packages: #45
-   [x] Provide API docs #58 
-   [x] Example for azure devops pipeline: #28

## Test support

-   [x] Test utilities for services (provide mocked dependencies): #37
-   [x] Test utilities for react components (provide mocked dependencies): #34
