### ISSUE TITLE
Tracking Issue M3.1

### ISSUE THREAD

**Issue by mbeckem** [open-pioneer/trails-starter#60]
# Tracking Issue

## Package compilation

- [x] open-pioneer/trails-starter#63
- [x] open-pioneer/trails-starter#64
- [x] open-pioneer/trails-starter#65
- [x] open-pioneer/trails-starter#66
- [x] open-pioneer/trails-starter#67
- [x] open-pioneer/trails-starter#68
- [x] open-pioneer/trails-starter#69
- [x] open-pioneer/trails-starter#70
- [x] open-pioneer/trails-starter#72
- [x] open-pioneer/trails-starter#81

## Vite plugin

- [x] open-pioneer/trails-starter#71

## Release Process

- [x] open-pioneer/trails-starter#73
- [x] open-pioneer/trails-starter#74
- [x] open-pioneer/trails-starter#75
- [x] open-pioneer/trails-starter#78

## Organization

- [x] open-pioneer/trails-starter#76
- [x] open-pioneer/trails-starter#77

## Features
 
- [x] open-pioneer/trails-starter#62
- [ ] Postponed: open-pioneer/trails-core-packages#44
- [x] open-pioneer/trails-starter#80
- [x] open-pioneer/trails-starter#84

## Bugs
- [ ] Reported in upstream project (vite): open-pioneer/trails-build-tools#61
